buildscript {
    ext.kotlin_version = "1.8.0"
    ext.poolakey_version = "2.2.0"
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group 'ir.cafebazaar.flutter_poolakey'
version '2.2.0-1.0.0-alpha01'

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}

android {
    namespace 'ir.cafebazaar.flutter_poolakey'
    compileSdkVersion 35

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildFeatures {
        buildConfig true
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        minSdkVersion 16
        //noinspection HighAppVersionCode
        versionCode 2002001001
        versionName "2.2.0-1.0.0-alpha01"
    }

    buildTypes {
        debug {
            buildConfigField "String", "POOLAKEY_VERSION", '"' + poolakey_version + '"'
        }
        release {
            buildConfigField "String", "POOLAKEY_VERSION", '"' + poolakey_version + '"'
        }
    }

    dependencies {
        implementation "com.github.cafebazaar.Poolakey:poolakey:$poolakey_version"
    }
}